! Winteracter resource identifiers. Created : 19/jún./2026     20:57:11
!
! This file is generated by the Winteracter resource editor.
! It should not be edited manually. It is also not advisable to load this
! file in a text editor, while working on the associated resource file,
! since this may prevent the resource identifiers file from being updated.
! To view the names and values of resource identifiers, use the
! "Identifier Names and Values" or "Used Identifiers" options on the
! resource editor's "View" menu. Both dialogs also include a "Copy id"
! button which allows identifier names to be copied via the clipboard.
! Opening this file in an editor should therefore not be necessary.
!
      MODULE RESID
      IMPLICIT NONE
      INTEGER, PARAMETER :: IDM_MAIN                     = 30001
      INTEGER, PARAMETER :: ID_SCREENSIZE                = 40001
      INTEGER, PARAMETER :: IDF_DEBUGTXT                 =  1001
      INTEGER, PARAMETER :: IDD_DEBUGMSG                 =   102
      INTEGER, PARAMETER :: ID_DEBUGOK                   =  1002
      INTEGER, PARAMETER :: ID_AUTO                      = 40002
      INTEGER, PARAMETER :: ID_320x240                   = 40003
      INTEGER, PARAMETER :: ID_640x480                   = 40004
      INTEGER, PARAMETER :: ID_800x600                   = 40005
      INTEGER, PARAMETER :: ID_1024x768                  = 40006
      INTEGER, PARAMETER :: ID_1152x864                  = 40007
      INTEGER, PARAMETER :: ID_1280x960                  = 40008
      INTEGER, PARAMETER :: ID_1400x1050                 = 40009
      INTEGER, PARAMETER :: ID_1600x1200                 = 40010
      INTEGER, PARAMETER :: ID_2048x1536                 = 40011
      INTEGER, PARAMETER :: ID_SPEED                     = 40012
      INTEGER, PARAMETER :: ID_SPEED1                    = 40013
      INTEGER, PARAMETER :: ID_SPEED2                    = 40014
      INTEGER, PARAMETER :: ID_SPEED3                    = 40015
      INTEGER, PARAMETER :: ID_SPEED4                    = 40016
      INTEGER, PARAMETER :: ID_SPEED5                    = 40017
      INTEGER, PARAMETER :: ID_DEV                       = 40018
      INTEGER, PARAMETER :: ID_BEEP                      = 40019
      INTEGER, PARAMETER :: IDD_GENBEEP                  =   101
      INTEGER, PARAMETER :: ID_GENBEEP_GEN               =  1003
      INTEGER, PARAMETER :: ID_GENBEEP_SAVE              =  1004
      INTEGER, PARAMETER :: ID_GENBEEP_PLAY              =  1005
      END MODULE RESID
