! Winteracter resource identifiers. Created : 28/aug./2026     10:53:28
!
! This file is generated by the Winteracter resource editor.
! It should not be edited manually. It is also not advisable to load this
! file in a text editor, while working on the associated resource file,
! since this may prevent the resource identifiers file from being updated.
! To view the names and values of resource identifiers, use the
! "Identifier Names and Values" or "Used Identifiers" options on the
! resource editor's "View" menu. Both dialogs also include a "Copy id"
! button which allows identifier names to be copied via the clipboard.
! Opening this file in an editor should therefore not be necessary.
!
      MODULE RESID
      IMPLICIT NONE
      INTEGER, PARAMETER :: IDM_MAIN                     = 30001
      INTEGER, PARAMETER :: ID_SCREENSIZE                = 40001
      INTEGER, PARAMETER :: IDF_DEBUGTXT                 =  1001
      INTEGER, PARAMETER :: IDD_DEBUGMSG                 =   102
      INTEGER, PARAMETER :: ID_DEBUGOK                   =  1002
      INTEGER, PARAMETER :: ID_AUTO                      = 40002
      INTEGER, PARAMETER :: ID_320x240                   = 40003
      INTEGER, PARAMETER :: ID_640x480                   = 40004
      INTEGER, PARAMETER :: ID_800x600                   = 40005
      INTEGER, PARAMETER :: ID_1024x768                  = 40006
      INTEGER, PARAMETER :: ID_1152x864                  = 40007
      INTEGER, PARAMETER :: ID_1280x960                  = 40008
      INTEGER, PARAMETER :: ID_1400x1050                 = 40009
      INTEGER, PARAMETER :: ID_1600x1200                 = 40010
      INTEGER, PARAMETER :: ID_2048x1536                 = 40011
      INTEGER, PARAMETER :: ID_SPEED                     = 40012
      INTEGER, PARAMETER :: ID_SPEED1                    = 40013
      INTEGER, PARAMETER :: ID_SPEED2                    = 40014
      INTEGER, PARAMETER :: ID_SPEED3                    = 40015
      INTEGER, PARAMETER :: ID_SPEED4                    = 40016
      INTEGER, PARAMETER :: ID_SPEED5                    = 40017
      INTEGER, PARAMETER :: ID_DEV                       = 40018
      INTEGER, PARAMETER :: ID_TIA_Noiser                = 40019
      INTEGER, PARAMETER :: IDD_GENBEEP                  =   101
      INTEGER, PARAMETER :: ID_GENBEEP_GEN               =  1003
      INTEGER, PARAMETER :: ID_GENBEEP_SAVE              =  1004
      INTEGER, PARAMETER :: ID_GENBEEP_PLAY              =  1005
      INTEGER, PARAMETER :: ID_TIAINPUT                  =  1006
      INTEGER, PARAMETER :: IDD_TIA                      =   104
      INTEGER, PARAMETER :: ID_TIAName                   =  1007
      INTEGER, PARAMETER :: ID_TIAErase                  =  1011
      INTEGER, PARAMETER :: ID_TIASave                   =  1012
      INTEGER, PARAMETER :: ID_TIAPlay                   =  1013
      INTEGER, PARAMETER :: ID_TIALoad                   =  1014
      INTEGER, PARAMETER :: IDF_STRING4                  =  1016
      INTEGER, PARAMETER :: ID_VGMLoad                   =  1008
      INTEGER, PARAMETER :: IDD_VGM2XXA                  =   105
      INTEGER, PARAMETER :: ID_XXASave                   =  1009
      INTEGER, PARAMETER :: ID_XXAPlay                   =  1010
      INTEGER, PARAMETER :: ID_XXAName                   =  1015
      INTEGER, PARAMETER :: ID_VGM2XXA                   = 40020
      INTEGER, PARAMETER :: ID_XXAStop                   =  1017
      INTEGER, PARAMETER :: ID_SoundInput                = 40021
      INTEGER, PARAMETER :: ID_SoundSettings             = 40022
      INTEGER, PARAMETER :: ID_InputSettings             = 40023
      INTEGER, PARAMETER :: IDF_SoundTrack               =  1018
      INTEGER, PARAMETER :: IDD_SoundSettings            =   106
      INTEGER, PARAMETER :: IDF_LABELSfxVol              =  1019
      INTEGER, PARAMETER :: IDF_SoundValue               =  1020
      INTEGER, PARAMETER :: IDF_MusicValue               =  1021
      INTEGER, PARAMETER :: IDF_MusicTrack               =  1022
      INTEGER, PARAMETER :: IDF_LABELMusicVol            =  1023
      INTEGER, PARAMETER :: IDF_MusicRadio1              =  1024
      INTEGER, PARAMETER :: IDF_MusicRadio2              =  1025
      INTEGER, PARAMETER :: IDF_HEX                      =  1026
      INTEGER, PARAMETER :: IDF_LPTPort                  =  1027
      INTEGER, PARAMETER :: ID_SoundOK                   =  1028
      INTEGER, PARAMETER :: ID_SoundCancel               =  1029
      INTEGER, PARAMETER :: ID_SoundReset                =  1030
      INTEGER, PARAMETER :: ID_SoundTest                 =  1031
      INTEGER, PARAMETER :: ID_MusicTest                 =  1032
      INTEGER, PARAMETER :: ID_MusicTest2                =  1033
      INTEGER, PARAMETER :: ID_MusicStop                 =  1034
      INTEGER, PARAMETER :: ID_MusicStop2                =  1035
      INTEGER, PARAMETER :: IDF_InputTester              =  1036
      INTEGER, PARAMETER :: IDD_InputSetter              =   107
      INTEGER, PARAMETER :: IDF_LabelButton              =  1037
      INTEGER, PARAMETER :: IDF_Pressed                  =  1038
      INTEGER, PARAMETER :: IDF_LabelDirs                =  1039
      INTEGER, PARAMETER :: IDF_JoyUp                    =  1040
      INTEGER, PARAMETER :: IDF_JoyDown                  =  1041
      INTEGER, PARAMETER :: IDF_JoyLeft                  =  1042
      INTEGER, PARAMETER :: IDF_JoyRight                 =  1043
      INTEGER, PARAMETER :: IDF_LabelJoyButt             =  1044
      INTEGER, PARAMETER :: IDF_Joy1                     =  1045
      INTEGER, PARAMETER :: IDF_Joy2                     =  1046
      INTEGER, PARAMETER :: IDF_Joy3                     =  1047
      INTEGER, PARAMETER :: IDF_Joy4                     =  1048
      INTEGER, PARAMETER :: IDF_Joy5                     =  1049
      INTEGER, PARAMETER :: IDF_Joy6                     =  1050
      INTEGER, PARAMETER :: IDF_JoySenseTrk              =  1051
      INTEGER, PARAMETER :: IDF_JoySenseVal              =  1052
      INTEGER, PARAMETER :: IDF_Analog                   =  1053
      INTEGER, PARAMETER :: ID_InputCancel               =  1054
      INTEGER, PARAMETER :: ID_InputOK                   =  1055
      INTEGER, PARAMETER :: ID_InputRestore              =  1056
      INTEGER, PARAMETER :: IDF_KeyboardGroup            =  1057
      INTEGER, PARAMETER :: IDF_JoystickGroup            =  1058
      INTEGER, PARAMETER :: IDF_LabelButtonName          =  1059
      INTEGER, PARAMETER :: IDF_LabelButtonName2         =  1060
      INTEGER, PARAMETER :: IDF_LabelButtonName3         =  1061
      INTEGER, PARAMETER :: IDF_LabelButtonName4         =  1062
      INTEGER, PARAMETER :: IDF_LabelButtonName5         =  1063
      INTEGER, PARAMETER :: IDF_LabelButtonName6         =  1064
      INTEGER, PARAMETER :: IDF_LabelButtonName7         =  1065
      INTEGER, PARAMETER :: IDF_LabelButtonName8         =  1066
      INTEGER, PARAMETER :: IDF_LabelButtonName9         =  1067
      INTEGER, PARAMETER :: IDF_LabelButtonName10        =  1068
      INTEGER, PARAMETER :: ID_AssignLeftKey             =  1069
      INTEGER, PARAMETER :: ID_AssignRightKey            =  1070
      INTEGER, PARAMETER :: ID_AssignUpKey               =  1071
      INTEGER, PARAMETER :: ID_AssignDownKey             =  1072
      INTEGER, PARAMETER :: ID_AssignAttackKey           =  1073
      INTEGER, PARAMETER :: ID_AssignChargeKey           =  1074
      INTEGER, PARAMETER :: ID_AssignSpell1Key           =  1075
      INTEGER, PARAMETER :: ID_AssignSpell2Key           =  1076
      INTEGER, PARAMETER :: ID_AssignSpell3Key           =  1077
      INTEGER, PARAMETER :: ID_AssignMenuKey             =  1078
      INTEGER, PARAMETER :: ID_AssignLeftJoy             =  1079
      INTEGER, PARAMETER :: ID_AssignRightJoy            =  1080
      INTEGER, PARAMETER :: ID_AssignUpJoy               =  1081
      INTEGER, PARAMETER :: ID_AssignDownJoy             =  1082
      INTEGER, PARAMETER :: ID_AssignAttackJoy           =  1083
      INTEGER, PARAMETER :: ID_AssignChargeJoy           =  1084
      INTEGER, PARAMETER :: ID_AssignSpell1Joy           =  1085
      INTEGER, PARAMETER :: ID_AssignSpell2Joy           =  1086
      INTEGER, PARAMETER :: ID_AssignSpell3Joy           =  1087
      INTEGER, PARAMETER :: ID_AssignMenuJoy             =  1088
      INTEGER, PARAMETER :: ID_BMP2XXP                   = 40024
      INTEGER, PARAMETER :: ID_BMPLoad                   =  1089
      INTEGER, PARAMETER :: IDD_BMP2XXP                  =   108
      INTEGER, PARAMETER :: ID_XXPSave                   =  1090
      INTEGER, PARAMETER :: ID_XXPName                   =  1091
      INTEGER, PARAMETER :: IDF_SpriteIndex              =  1092
      INTEGER, PARAMETER :: IDF_XXPLABEL1                =  1093
      INTEGER, PARAMETER :: IDF_ANIM                     =  1094
      INTEGER, PARAMETER :: IDF_XXPLABEL2                =  1095
      INTEGER, PARAMETER :: IDF_TRANS                    =  1096
      INTEGER, PARAMETER :: IDF_TransColor               =  1097
      INTEGER, PARAMETER :: IDF_ColorPick                =  1098
      INTEGER, PARAMETER :: IDF_XXPLABEL3                =  1099
      INTEGER, PARAMETER :: IDF_FilterInd                =  1100
      INTEGER, PARAMETER :: IDF_TransTrk                 =  1101
      INTEGER, PARAMETER :: ID_DisplayPalette            = 40025
      END MODULE RESID
